version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
    environment:
      - NODE_ENV=development
    networks:
      - vible-network

  # Backend API server
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./server.js:/app/server.js:ro
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - vible-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - vible-network

networks:
  vible-network:
    driver: bridge

volumes:
  data:
    driver: local
